---
name: EMQX
version: 5.10.2
slug: emqx
description: Version 5.10.2
url: https://github.com/raphael1688dev/addon-emqx
startup: services
ingress: true
ingress_port: 18083
ingress_stream: true
init: false
panel_icon: mdi:pipe
panel_title: EMQX
arch:
  - aarch64
  - amd64
map:
  - ssl
  - addon_config:rw
options:
  env_vars: []
host_network: true
schema:
  env_vars:
    - name: match(^EMQX_([A-Z0-9_])+$)
      value: str
